"""Add ServiceCatalog OrderService discount to orders

Revision ID: f8b9be1dcf67
Revises: 68384af9ec08
Create Date: 2026-04-05 13:43:41.125098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b9be1dcf67'
down_revision = '68384af9ec08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_catalog',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('tier', sa.String(length=10), nullable=False),
    sa.Column('price_auto', sa.Integer(), nullable=False),
    sa.Column('price_camioneta', sa.Integer(), nullable=False),
    sa.Column('price_moto', sa.Integer(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('order_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('service_code', sa.String(length=30), nullable=False),
    sa.Column('price_snap', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['service_code'], ['service_catalog.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('discount', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('discount')
        batch_op.drop_column('package_type')

    op.drop_table('order_service')
    op.drop_table('service_catalog')
    # ### end Alembic commands ###
